---
- hosts: webservers
  become_user: root
  become: yes
  tasks:
  - name: gather facts from web servers
    amazon.aws.ec2_metadata_facts:

- hosts: loadbalancers
  become_user: root
  become: yes
  pre_tasks:

  - name: Setup backendservers
    set_fact:
      haproxy_backend_servers_dynamic: "{{ groups['webservers'] | map('extract', hostvars, ['ansible_ec2_public_ipv4']) | map('regex_replace', '^(.*)$','\\1:80') | list  }}"

  - name: update package list
    ansible.builtin.apt:
      update_cache: yes

  roles:
  - role: geerlingguy.haproxy
    haproxy_version: "{{ '1.4' if '1.4.' in haproxy_version_result.stdout else '1.5' }}"
    haproxy_backend_servers:
      - "{{ haproxy_backend_servers_dynamic }}"
