---
- name: show return value of command module
  hosts: servers
  tasks:
    - name: capture output of id command
      ansible.builtin.command: id -un
      register: login
    - debug:
        #var: login
        msg: "User login = {{ login.stdout }}"
