---
- name: install Apache
  apt: name=apache2 update_cache=yes state=latest
- name: ensure Apache is running
  service: name=apache2 state=started enabled=yes
- name: capture output of id command
  command: id -un
  register: login
- name: create website file
  template:
    dest: "/var/www/html/index.html"
    src: index.html.j2
- name: set permissions
  file:
    path: "/var/www"
    state: directory
    recurse: yes
    mode: '0755'
